### ISSUE TITLE
Include all unecessary config and installation files in gitignore

### ISSUE THREAD

**Issue by AlineTheAlien** [MI-390/mRides-app#58]
This includes a lot of the Firebase installation files that were included in the Chat pull request

**Comment by AlineTheAlien** [comment]
@nim442 Was this fixed yet?

**Comment by nim442** [comment]
I added some of the files to .gitignore, however that only works for files that are not already commited. You would have to manually delete them after adding them to gitignore and this might create unwanted consequences on other people's machine so I thought it best to leave those files as they are for now. (since this doesn't hinder our workflow at all as many of these files are autogenerated)
